FROM python:3.12-slim

# libpcap нужен scapy для захвата пакетов; tcpdump — для отладки
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpcap-dev tcpdump gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir scapy netifaces

WORKDIR /app
COPY tproc.py .

# Запуск от root (нужен для raw sockets), scapy требует привилегий
CMD ["python", "tproc.py"]
