version: "2.4"

services:

  # --------------------------------------------------------
  # GATE — Reverse Proxy with IP Filtering
  # --------------------------------------------------------
  gate:
    build:
      context: ../gate
      dockerfile: Dockerfile
    container_name: gate
    ports:
      - "8081:8080"
    depends_on:
      - cnss
      - error-server
    networks:
      - swp-net
    restart: unless-stopped

  # --------------------------------------------------------
  # ERROR SERVER — Page for Blocked IPs
  # --------------------------------------------------------
  error-server:
    build:
      context: ../error_server
      dockerfile: Dockerfile
    container_name: error_server
    expose:
      - "5000"
    networks:
      - swp-net
    restart: unless-stopped
